export * from "./button/Button";
export * from "./texts/H1";
export * from "./texts/H2";
export * from "./texts/H3";
export * from "./texts/H5";
export * from "./texts/SpanBase";
export * from "./texts/TextBase";
export * from "./wrappers/Box";
export * from "./wrappers/SectionWapper";
export * from "./headerSection/Header";
export * from "./button/Button";
export * from "./button/Btn";
export * from "./cards/Card";
export * from "./cards/CardsMobile";
export * from "./headline/HeadlineH1";
export * from "./headline/HeadlineH2";
export * from "./headline/HeadllineH3";
export * from "./isYogaForYou/ISYoga4U";
export * from "./isYogaForYou/IsYoga4USection";
export * from "./monthPlans/MonthPlanPart";
export * from "./monthPlans/MonthPlansSection";
export * from "./paymentSection/PaymentSection";
export * from "./phonesSection/phoneSection";
export * from "./questionsSection/QuestionsPart";
export * from "./questionsSection/QuestionsSection";
export * from "./yogaProgramSection/YogaProgramPart";
export * from "./yogaProgramSection/YogaProgramSection";

// Kodėl reikia exportinti taip failus?
